### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '-f'

### ISSUE THREAD

**Issue by ilray88** [bojone/SPACES#16]
#### 运行测试代码
from final import *
summary = predict(text, topk=3)
print(summary)

#### 出现以下错误

ValueError                                Traceback (most recent call last)   
<ipython-input-6-81b1c2426563> in <module>()  
----> 1 from final import *  
      2 summary = predict(text, topk=3)  
      3 print(summary)  
  
1 frames
/content/drive/My Drive/python_work/SPACES/extract_model.py in <module>()
     27     fold = 0
     28 else:
---> 29     fold = int(sys.argv[1])
     30 
     31 

ValueError: invalid literal for int() with base 10: '-f'

####运行环境Colab
tensorflow==1.14
bert4keras==0.9.8
keras==2.3.1

**Comment by zmz125** [comment]
请问解决了吗？
