### ISSUE TITLE
预测的时候没在GPU跑

### ISSUE THREAD

**Issue by JJack0812** [bojone/SPACES#19]
我在运行`extract_model.py`文件时，训练阶段是可以跑GPU的，但是在评估阶段，`model.predict`函数没有使用GPU，GPU的功率没有上去。并且14份的训练时间和1份的预测时间大致相等，我猜测是没有在GPU上跑。
然而另一份`seq2seq_convert.py`代码，纯预测阶段，是在GPU上跑的，跑的就很快。

希望苏神不吝赐教！

**Comment by bojone** [comment]
既然确认`extract_model.py`在GPU跑，那么最后的预测显然也会在gpu跑。你的所谓猜测依据只不过是“慢”、“功率没上去”，不能证明没有使用GPU。

事实上，预测过程就是这么慢的～因为要逐个样本自回归地解码

**Comment by JJack0812** [comment]
> 既然确认`extract_model.py`在GPU跑，那么最后的预测显然也会在gpu跑。你的所谓猜测依据只不过是“慢”、“功率没上去”，不能证明没有使用GPU。
> 
> 事实上，预测过程就是这么慢的～因为要逐个样本自回归地解码

ok了解了。
btw，抽取模型的预测不需要自回归解码吧？
