### ISSUE TITLE
训练时GPU使用很低，CPU占用很高的问题

### ISSUE THREAD

**Issue by young-yhx** [bojone/SPACES#40]
苏神您好，在运行seq2seq_model.py进行生成训练的时候，GPU只占用了257M，但CPU占用超级大，训练的时候一个epoch要话费2h左右，我服务器有四张40G的卡，我推断是没用到GPU进行训练，我直接os.environ["CUDA_VISIBLE_DEVICES"] = "1"的时候并没有得到改善，还是大量用到的是CPU。请问代码如何设置使用GPU进行训练，加快训练速度，望解答，谢谢您！

**Comment by young-yhx** [comment]
> 苏神您好，在运行seq2seq_model.py进行生成训练的时候，GPU只占用了257M，但CPU占用超级大，训练的时候一个epoch要话费2h左右，我服务器有四张40G的卡，我推断是没用到GPU进行训练，我直接os.environ["CUDA_VISIBLE_DEVICES"] = "1"的时候并没有得到改善，还是大量用到的是CPU。请问代码如何设置使用GPU进行训练，加快训练速度，望解答，谢谢您！

**Comment by young-yhx** [comment]
> 苏神您好，在运行seq2seq_model.py进行生成训练的时候，GPU只占用了257M，但CPU占用超级大，训练的时候一个epoch要话费2h左右，我服务器有四张40G的卡，我推断是没用到GPU进行训练，我直接os.environ["CUDA_VISIBLE_DEVICES"] = "1"的时候并没有得到改善，还是大量用到的是CPU。请问代码如何设置使用GPU进行训练，加快训练速度，望解答，谢谢您！

**Comment by balabanahei** [comment]
兄弟，请问解决了吗，
